### ISSUE TITLE
V2: NiProducer terminates after reset

### ISSUE THREAD

**Issue by arummler** [eudaq/eudaq#451]
There was an error and after issuing a reset the NiProducer immediately terminated (reproducible).

**Comment by arummler** [comment]
The error was that it cannot connect to ANEMONE. With eudaq1 it worked just now. The changes in commit 2334069a2714 need to be checked.

**Comment by arummler** [comment]
@eyiliu @dreyling Did you experience any problems during your test this week?

**Comment by dreyling** [comment]
@arummler yes and we fixed it, we will push it to the master next week.

**Comment by arummler** [comment]
The no-connect resulted from the new split into init and conf step. I was not aware of it and had my config still only in conf. Thus it was set to localhost (and there is no warning...). The reset problem still applies.

**Comment by dreyling** [comment]
@arummler  the code is now in the master. The reset should work now..
Yes, and the connection/disconnection happen now in the init/reset.
